
export const categories = [
  { id: 'basics',        name: 'Advertising Basics',        icon: '📚', color: 'from-blue-500 to-purple-600' },
  { id: 'history',       name: 'History of AdTech',         icon: '🕰️', color: 'from-green-500 to-teal-600' },
  { id: 'ecosystem',     name: 'Ad Ecosystem',              icon: '🌐', color: 'from-amber-500 to-orange-600' },
  { id: 'ad_serving',    name: 'Ad Serving',                icon: '🖥️', color: 'from-red-500 to-pink-600' },
  { id: 'targeting',     name: 'Targeting & Budget',        icon: '🎯', color: 'from-indigo-500 to-blue-600' },
  { id: 'media_buying',  name: 'Media Buying',              icon: '💼', color: 'from-emerald-500 to-cyan-600' },
  { id: 'identity',      name: 'User Identification',       icon: '🆔', color: 'from-yellow-500 to-red-600' },
  { id: 'data',          name: 'Data & DMPs',               icon: '💾', color: 'from-gray-500 to-gray-700' },
  { id: 'privacy',       name: 'Privacy & Compliance',      icon: '🔐', color: 'from-pink-500 to-purple-600' },
  { id: 'fraud_view',    name: 'Fraud & Viewability',       icon: '🚨', color: 'from-cyan-500 to-indigo-600' },
];

export const quizData = {
  basics: [
    { question: "Who is the publisher?", options: ["The advertiser", "The website owner", "AdTech platform", "End user"], correct: 1 },
    { question: "What does 'AdTech' refer to?", options: ["Marketing trends", "Advertising technology", "Branding tools", "Budget formats"], correct: 1 },
    { question: "Who pays for ads?", options: ["Advertiser", "Publisher", "DSP", "Agency"], correct: 0 },
    { question: "A publisher is:", options: ["Ad buyer", "Website/app owner", "Data broker", "Ad exchange"], correct: 1 },
    { question: "IAB stands for:", options: ["Interactive Ads Bureau", "Internet Ad Board", "Interactive Ad Business", "Internet Ads Bureau"], correct: 0 },
    { question: "CPM means:", options: ["Cost per mile", "Click per mile", "Cost per mille", "Click per metric"], correct: 2 },
    { question: "CTR measures:", options: ["Cost to revenue", "Click-through rate", "Conversion time", "Creative tags"], correct: 1 },
    { question: "Rich media supports:", options: ["Static images only", "HTML5 animations", "Text banners", "Audio only"], correct: 1 },
    { question: "Retargeting means:", options: ["New users only", "Target past visitors", "Drive organic traffic", "Push notifications"], correct: 1 },
    { question: "Who runs ad campaigns?", options: ["Publisher", "Advertiser", "Both", "Government"], correct: 1 },
  ],
  history: [
    { question: "Digital ads began in:", options: ["1970s", "1990s", "2000s", "2010s"], correct: 1 },
    { question: "First banner ad was:", options: ["1994", "1998", "2000", "2002"], correct: 0 },
    { question: "First AdTech companies use:", options: ["Cookies", "HTML5", "Mobile IDs", "AI"], correct: 0 },
    { question: "Search ads launched in:", options: ["1995", "1998", "2002", "2005"], correct: 2 },
    { question: "Programmatic RTB rose around:", options: ["2000", "2007", "2010", "2015"], correct: 2 },
    { question: "Walled gardens began as:", options: ["YouTube", "Facebook", "Google", "Yahoo"], correct: 2 },
    { question: "Header bidding started around:", options: ["2010", "2012", "2015", "2018"], correct: 2 },
    { question: "First mobile ads appeared in:", options: ["2000", "2005", "2010", "2015"], correct: 1 },
    { question: "Ad blockers became popular:", options: ["2010s", "2000s", "1990s", "1980s"], correct: 0 },
    { question: "GDPR enforcement started:", options: ["2016", "2018", "2020", "2022"], correct: 1 },
  ],
  ecosystem: [
    { question: "DSP stands for:", options: ["Demand Side Platform", "Data Sell Platform", "Display Sell Platform", "Demand SSP"], correct: 0 },
    { question: "SSP is on:", options: ["Sell‑side", "Buy‑side", "Ad exchange", "Advertiser"], correct: 0 },
    { question: "Ad exchange is:", options: ["Publish ad content", "Auction venue", "Analytics tool", "Tag manager"], correct: 1 },
    { question: "Walled garden example:", options: ["DSP", "Google Ads", "SSP", "Data broker"], correct: 1 },
    { question: "Standardization by:", options: ["W3C", "IAB", "ISPs", "Browsers"], correct: 1 },
    { question: "Publisher makes money via:", options: ["Buying media", "Selling inventory", "Tracking users", "Providing analytics"], correct: 1 },
    { question: "Advertiser buys through:", options: ["SSP", "DSP", "Publisher", "Browser"], correct: 1 },
    { question: "Intermediary example:", options: ["Facebook page", "Ad exchange", "User agent", "Tag"], correct: 1 },
    { question: "Buy‑side =", options: ["Publisher", "Advertiser", "Browser", "IAB"], correct: 1 },
    { question: "Sell‑side =", options: ["DSP", "SSP", "Ad agency", "Advertiser"], correct: 1 },
  ],
  ad_serving: [
    { question: "Ad server manages:", options: ["Campaign delivery", "User IDs", "Feed uploads", "Privacy policy"], correct: 0 },
    { question: "Tag is:", options: ["HTML snippet", "Image file", "Video file", "CSS script"], correct: 0 },
    { question: "1st‑party server hosted by:", options: ["Publisher", "DSP", "SSP", "IAB"], correct: 0 },
    { question: "3rd‑party server tracks:", options: ["Only impressions", "IDs across sites", "Budget only", "Feeds"], correct: 1 },
    { question: "Ad request starts when:", options: ["Page loads", "Campaign ends", "Budget is spent", "User clicks"], correct: 0 },
    { question: "Creative is:", options: ["Ad content", "User profile", "SSP", "DSP"], correct: 0 },
    { question: "Report shows:", options: ["Clicks/impressions", "Server code", "Campaign script", "API keys"], correct: 0 },
    { question: "Latency in serving leads to:", options: ["Faster ads", "Delays", "Lower budget", "Higher bids"], correct: 1 },
    { question: "Ad server tech stack includes:", options: ["Database/logging/tagging", "DSP code", "Cookie banners", "Game engine"], correct: 0 },
    { question: "Header bidding bypasses:", options: ["Auction", "Waterfall", "Tag", "SSP"], correct: 1 },
  ],
  targeting: [
    { question: "Contextual targets using:", options: ["User history", "Page content", "Device type", "Bid price"], correct: 1 },
    { question: "Behavioral means:", options: ["Page text", "User actions", "IP only", "Creative only"], correct: 1 },
    { question: "Retargeting uses:", options: ["New users", "Past visitors", "IP geolocation", "Device type"], correct: 1 },
    { question: "Dayparting controls:", options: ["Creative", "Time of day", "User age", "Budget only"], correct: 1 },
    { question: "Taxonomy from:", options: ["IAB", "DSP", "Advertiser", "Publisher"], correct: 0 },
    { question: "Geo-targeting uses:", options: ["IP", "Cookie", "Tag", "Creative"], correct: 0 },
    { question: "Keyword targeting uses:", options: ["Browser history", "Page keywords", "User gender", "Device type"], correct: 1 },
    { question: "Budget pacing prevents:", options: ["Early spend", "Creative errors", "Latency", "Fraud"], correct: 0 },
    { question: "Device targeting includes:", options: ["Device model", "User email", "Page URL", "Campaign ID"], correct: 0 },
    { question: "Section & URL targeting:", options: ["Site segment", "Creative type", "User list", "Bid type"], correct: 0 },
  ],
  media_buying: [
    { question: "RTB stands for:", options: ["Real‑Time Bidding", "Retargeting Tool Bids", "Responsive Tag Bids", "Rich Tag Bidding"], correct: 0 },
    { question: "PMP means:", options: ["Private Marketplace", "Publish‑mediated Program", "Platform Media Program", "Programmatic Mediator Plan"], correct: 0 },
    { question: "Header bidding vs waterfall:", options: ["One auction vs sequential", "Video vs display", "Mobile vs desktop", "Buy‑side vs sell‑side"], correct: 0 },
    { question: "First‑price auction:", options: ["Highest pays own bid", "Highest pays second price", "Publisher pays DSP", "No bid"], correct: 0 },
    { question: "Second‑price auction:", options: ["Pays 2nd highest + epsilon", "Pays own bid", "Pays reserve price", "No charge"], correct: 0 },
    { question: "Waterfall uses:", options: ["Sequential SSPs", "Header auction", "Cookie sync", "Analytics"], correct: 0 },
    { question: "Programmatic direct excludes:", options: ["RTB", "DSP", "SSP", "Publisher"], correct: 0 },
    { question: "Manual buying is:", options: ["Non-automated", "AI-driven", "Realtime", "DSP-based"], correct: 0 },
    { question: "Auction dynamics include:", options: ["Hard/soft floors", "Privacy settings", "Geo‑targeting", "Creative formats"], correct: 0 },
    { question: "Private marketplace uses:", options: ["Invite‑only RTB", "Open auction", "Manual insertion", "CDN"], correct: 0 },
  ],
  identity: [
    { question: "Cookies store:", options: ["User IDs", "Creative", "Tags", "Analytics only"], correct: 0 },
    { question: "Device fingerprinting uses:", options: ["IP, browser info", "Creative types", "Tag patterns", "Budget amounts"], correct: 0 },
    { question: "IDFA belongs to:", options: ["iOS devices", "Android devices", "Desktop browsers", "SSPs"], correct: 0 },
    { question: "AAID is:", options: ["Android ID", "Apple ID", "Amazon ID", "Advertiser ID"], correct: 0 },
    { question: "Deterministic match means:", options: ["Exact match", "Probable match", "Cookie sync only", "Anonymous match"], correct: 0 },
    { question: "Probabilistic uses:", options: ["Inference", "IDs", "SDK only", "IP only"], correct: 0 },
    { question: "Most browsers block 3rd‑party cookies:", options: ["True", "False", "Only Safari", "No"], correct: 0 },
    { question: "ID Graph is:", options: ["Cross‑device ID map", "DSP tag", "Analytics tool", "Publisher feed"], correct: 0 },
    { question: "Evercookies are:", options: ["Hard to delete", "Simple text feed", "Consent tag", "Analytics report"], correct: 0 },
    { question: "Fingerprinting is:", options: ["Device signature", "Cookie type", "Budget method", "Auction type"], correct: 0 },
  ],
  data: [
    { question: "DMP stands for:", options: ["Data Management Platform", "Digital Media Platform", "Display Marketing Platform", "Demand Management Platform"], correct: 0 },
    { question: "1st‑party data is from:", options: ["Own site/app", "Third‑party provider", "DSP", "Publisher network"], correct: 0 },
    { question: "Second‑party data is:", options: ["Partner data", "Public data", "CDP data", "DSP data"], correct: 0 },
    { question: "Third‑party data is:", options: ["Purchased segments", "Own CRM", "Partner-only", "Site logs"], correct: 0 },
    { question: "Onboarding means:", options: ["Uploading offline data", "Serving ads", "Tagging URLs", "Bid upload"], correct: 0 },
    { question: "Audience segmentation means:", options: ["Grouping users", "Creating creatives", "Pricing inventory", "Collecting tags"], correct: 0 },
    { question: "Pixels collect:", options: ["User behavior", "Bid prices", "Budget details", "Ad creatives"], correct: 0 },
    { question: "APIs help to:", options: ["Connect systems", "Serve ads", "Track IDs only", "Block cookies"], correct: 0 },
    { question: "Data enrichment means:", options: ["Enhancing profiles", "Budget pacing", "Ad serving", "Tagging only"], correct: 0 },
    { question: "CDP =", options: ["Customer Data Platform", "Creative Design Platform", "Cookie Data Processor", "Campaign Delivery Platform"], correct: 0 },
  ],
  privacy: [
    { question: "GDPR applies to:", options: ["EU personal data", "Global web", "US only", "Mobile only"], correct: 0 },
    { question: "CCPA is from:", options: ["California", "Canada", "China", "Europe"], correct: 0 },
    { question: "PII =", options: ["Personally Identifiable Information", "Private IP Info", "Public ID Index", "Personal Internet Identity"], correct: 0 },
    { question: "ATT from Apple:", options: ["App Tracking Transparency", "Ad Tech Tool", "Analytics Tag Token", "Automated Tracking Tool"], correct: 0 },
    { question: "Safari ITP blocks:", options: ["3rd‑party cookies", "1st‑party cookies", "HTML5 storage", "Device IDs"], correct: 0 },
    { question: "Chrome plans to kill:", options: ["3rd‑party cookies", "First‑party cookies", "Ad tags", "CSS"], correct: 0 },
    { question: "Opt‑out means user:", options: ["Declines behavioral ads", "Accepts cookies", "Clicks banners", "Shares data"], correct: 0 },
    { question: "Ad blocker blocks:", options: ["Ads/scripts", "Campaigns", "Bid requests", "Audience segments"], correct: 0 },
    { question: "SameSite cookie restricts:", options: ["Cross‑site sending", "Budget data", "Creative size", "DSP access"], correct: 0 },
    { question: "Privacy Sandbox is by:", options: ["Google Chrome", "Safari", "Firefox", "Edge"], correct: 0 },
  ],
  fraud_view: [
    { question: "Ad fraud type – bot traffic:", options: ["Automated fake visits", "Real human clicks", "Browser cookies", "Mobile IDs"], correct: 0 },
    { question: "Domain spoofing is:", options: ["Misrepresenting site", "Tag error", "Creative fail", "Budget leak"], correct: 0 },
    { question: "Viewability standard is:", options: ["50% for 1s", "100% for 1s", "5% for 3s", "75% for 2s"], correct: 0 },
    { question: "Non‑human traffic =", options: ["Bots", "Users", "Cookies", "Tags"], correct: 0 },
    { question: "Fraud hurts:", options: ["Advertiser ROI", "Campaign timing", "Creative size", "Volume only"], correct: 0 },
    { question: "Viewable impression counts when:", options: ["50% pixels visible", "Page logs in", "User clicks", "Cookie sets"], correct: 0 },
    { question: "Ad stacking =", options: ["Multiple ads layered", "Tag overlap", "ID sync", "Frequency cap"], correct: 0 },
    { question: "Click fraud is:", options: ["Fake clicks", "Correct clicks", "Creative clicks", "Audio clicks"], correct: 0 },
    { question: "Ad fraud defense uses:", options: ["Detection tools", "Creative tags", "Bid increase", "1st‑party data only"], correct: 0 },
    { question: "Invalid traffic =", options: ["Bot/human invalid", "All traffic", "Creative only", "Tag only"], correct: 0 },
  ],
};

