
// export const categories = [
//   { id: 'basics',        name: 'Advertising Basics',        icon: '📚', color: 'from-blue-500 to-purple-600' },
//   { id: 'history',       name: 'History of AdTech',         icon: '🕰️', color: 'from-green-500 to-teal-600' },
//   { id: 'ecosystem',     name: 'Ad Ecosystem',              icon: '🌐', color: 'from-amber-500 to-orange-600' },
//   { id: 'ad_serving',    name: 'Ad Serving',                icon: '🖥️', color: 'from-red-500 to-pink-600' },
//   { id: 'targeting',     name: 'Targeting & Budget',        icon: '🎯', color: 'from-indigo-500 to-blue-600' },
//   { id: 'media_buying',  name: 'Media Buying',              icon: '💼', color: 'from-emerald-500 to-cyan-600' },
//   { id: 'identity',      name: 'User Identification',       icon: '🆔', color: 'from-yellow-500 to-red-600' },
//   { id: 'data',          name: 'Data & DMPs',               icon: '💾', color: 'from-gray-500 to-gray-700' },
//   { id: 'privacy',       name: 'Privacy & Compliance',      icon: '🔐', color: 'from-pink-500 to-purple-600' },
//   { id: 'fraud_view',    name: 'Fraud & Viewability',       icon: '🚨', color: 'from-cyan-500 to-indigo-600' },
// ];

// export const quizData = {
//   basics: [
//     { question: "Who is the publisher?", options: ["The advertiser", "The website owner", "AdTech platform", "End user"], correct: 1 },
//     { question: "What does 'AdTech' refer to?", options: ["Marketing trends", "Advertising technology", "Branding tools", "Budget formats"], correct: 1 },
//     { question: "Who pays for ads?", options: ["Advertiser", "Publisher", "DSP", "Agency"], correct: 0 },
//     { question: "A publisher is:", options: ["Ad buyer", "Website/app owner", "Data broker", "Ad exchange"], correct: 1 },
//     { question: "IAB stands for:", options: ["Interactive Ads Bureau", "Internet Ad Board", "Interactive Ad Business", "Internet Ads Bureau"], correct: 0 },
//     { question: "CPM means:", options: ["Cost per mile", "Click per mile", "Cost per mille", "Click per metric"], correct: 2 },
//     { question: "CTR measures:", options: ["Cost to revenue", "Click-through rate", "Conversion time", "Creative tags"], correct: 1 },
//     { question: "Rich media supports:", options: ["Static images only", "HTML5 animations", "Text banners", "Audio only"], correct: 1 },
//     { question: "Retargeting means:", options: ["New users only", "Target past visitors", "Drive organic traffic", "Push notifications"], correct: 1 },
//     { question: "Who runs ad campaigns?", options: ["Publisher", "Advertiser", "Both", "Government"], correct: 1 },
//   ],
//   history: [
//     { question: "Digital ads began in:", options: ["1970s", "1990s", "2000s", "2010s"], correct: 1 },
//     { question: "First banner ad was:", options: ["1994", "1998", "2000", "2002"], correct: 0 },
//     { question: "First AdTech companies use:", options: ["Cookies", "HTML5", "Mobile IDs", "AI"], correct: 0 },
//     { question: "Search ads launched in:", options: ["1995", "1998", "2002", "2005"], correct: 2 },
//     { question: "Programmatic RTB rose around:", options: ["2000", "2007", "2010", "2015"], correct: 2 },
//     { question: "Walled gardens began as:", options: ["YouTube", "Facebook", "Google", "Yahoo"], correct: 2 },
//     { question: "Header bidding started around:", options: ["2010", "2012", "2015", "2018"], correct: 2 },
//     { question: "First mobile ads appeared in:", options: ["2000", "2005", "2010", "2015"], correct: 1 },
//     { question: "Ad blockers became popular:", options: ["2010s", "2000s", "1990s", "1980s"], correct: 0 },
//     { question: "GDPR enforcement started:", options: ["2016", "2018", "2020", "2022"], correct: 1 },
//   ],
//   ecosystem: [
//     { question: "DSP stands for:", options: ["Demand Side Platform", "Data Sell Platform", "Display Sell Platform", "Demand SSP"], correct: 0 },
//     { question: "SSP is on:", options: ["Sell‑side", "Buy‑side", "Ad exchange", "Advertiser"], correct: 0 },
//     { question: "Ad exchange is:", options: ["Publish ad content", "Auction venue", "Analytics tool", "Tag manager"], correct: 1 },
//     { question: "Walled garden example:", options: ["DSP", "Google Ads", "SSP", "Data broker"], correct: 1 },
//     { question: "Standardization by:", options: ["W3C", "IAB", "ISPs", "Browsers"], correct: 1 },
//     { question: "Publisher makes money via:", options: ["Buying media", "Selling inventory", "Tracking users", "Providing analytics"], correct: 1 },
//     { question: "Advertiser buys through:", options: ["SSP", "DSP", "Publisher", "Browser"], correct: 1 },
//     { question: "Intermediary example:", options: ["Facebook page", "Ad exchange", "User agent", "Tag"], correct: 1 },
//     { question: "Buy‑side =", options: ["Publisher", "Advertiser", "Browser", "IAB"], correct: 1 },
//     { question: "Sell‑side =", options: ["DSP", "SSP", "Ad agency", "Advertiser"], correct: 1 },
//   ],
//   ad_serving: [
//     { question: "Ad server manages:", options: ["Campaign delivery", "User IDs", "Feed uploads", "Privacy policy"], correct: 0 },
//     { question: "Tag is:", options: ["HTML snippet", "Image file", "Video file", "CSS script"], correct: 0 },
//     { question: "1st‑party server hosted by:", options: ["Publisher", "DSP", "SSP", "IAB"], correct: 0 },
//     { question: "3rd‑party server tracks:", options: ["Only impressions", "IDs across sites", "Budget only", "Feeds"], correct: 1 },
//     { question: "Ad request starts when:", options: ["Page loads", "Campaign ends", "Budget is spent", "User clicks"], correct: 0 },
//     { question: "Creative is:", options: ["Ad content", "User profile", "SSP", "DSP"], correct: 0 },
//     { question: "Report shows:", options: ["Clicks/impressions", "Server code", "Campaign script", "API keys"], correct: 0 },
//     { question: "Latency in serving leads to:", options: ["Faster ads", "Delays", "Lower budget", "Higher bids"], correct: 1 },
//     { question: "Ad server tech stack includes:", options: ["Database/logging/tagging", "DSP code", "Cookie banners", "Game engine"], correct: 0 },
//     { question: "Header bidding bypasses:", options: ["Auction", "Waterfall", "Tag", "SSP"], correct: 1 },
//   ],
//   targeting: [
//     { question: "Contextual targets using:", options: ["User history", "Page content", "Device type", "Bid price"], correct: 1 },
//     { question: "Behavioral means:", options: ["Page text", "User actions", "IP only", "Creative only"], correct: 1 },
//     { question: "Retargeting uses:", options: ["New users", "Past visitors", "IP geolocation", "Device type"], correct: 1 },
//     { question: "Dayparting controls:", options: ["Creative", "Time of day", "User age", "Budget only"], correct: 1 },
//     { question: "Taxonomy from:", options: ["IAB", "DSP", "Advertiser", "Publisher"], correct: 0 },
//     { question: "Geo-targeting uses:", options: ["IP", "Cookie", "Tag", "Creative"], correct: 0 },
//     { question: "Keyword targeting uses:", options: ["Browser history", "Page keywords", "User gender", "Device type"], correct: 1 },
//     { question: "Budget pacing prevents:", options: ["Early spend", "Creative errors", "Latency", "Fraud"], correct: 0 },
//     { question: "Device targeting includes:", options: ["Device model", "User email", "Page URL", "Campaign ID"], correct: 0 },
//     { question: "Section & URL targeting:", options: ["Site segment", "Creative type", "User list", "Bid type"], correct: 0 },
//   ],
//   media_buying: [
//     { question: "RTB stands for:", options: ["Real‑Time Bidding", "Retargeting Tool Bids", "Responsive Tag Bids", "Rich Tag Bidding"], correct: 0 },
//     { question: "PMP means:", options: ["Private Marketplace", "Publish‑mediated Program", "Platform Media Program", "Programmatic Mediator Plan"], correct: 0 },
//     { question: "Header bidding vs waterfall:", options: ["One auction vs sequential", "Video vs display", "Mobile vs desktop", "Buy‑side vs sell‑side"], correct: 0 },
//     { question: "First‑price auction:", options: ["Highest pays own bid", "Highest pays second price", "Publisher pays DSP", "No bid"], correct: 0 },
//     { question: "Second‑price auction:", options: ["Pays 2nd highest + epsilon", "Pays own bid", "Pays reserve price", "No charge"], correct: 0 },
//     { question: "Waterfall uses:", options: ["Sequential SSPs", "Header auction", "Cookie sync", "Analytics"], correct: 0 },
//     { question: "Programmatic direct excludes:", options: ["RTB", "DSP", "SSP", "Publisher"], correct: 0 },
//     { question: "Manual buying is:", options: ["Non-automated", "AI-driven", "Realtime", "DSP-based"], correct: 0 },
//     { question: "Auction dynamics include:", options: ["Hard/soft floors", "Privacy settings", "Geo‑targeting", "Creative formats"], correct: 0 },
//     { question: "Private marketplace uses:", options: ["Invite‑only RTB", "Open auction", "Manual insertion", "CDN"], correct: 0 },
//   ],
//   identity: [
//     { question: "Cookies store:", options: ["User IDs", "Creative", "Tags", "Analytics only"], correct: 0 },
//     { question: "Device fingerprinting uses:", options: ["IP, browser info", "Creative types", "Tag patterns", "Budget amounts"], correct: 0 },
//     { question: "IDFA belongs to:", options: ["iOS devices", "Android devices", "Desktop browsers", "SSPs"], correct: 0 },
//     { question: "AAID is:", options: ["Android ID", "Apple ID", "Amazon ID", "Advertiser ID"], correct: 0 },
//     { question: "Deterministic match means:", options: ["Exact match", "Probable match", "Cookie sync only", "Anonymous match"], correct: 0 },
//     { question: "Probabilistic uses:", options: ["Inference", "IDs", "SDK only", "IP only"], correct: 0 },
//     { question: "Most browsers block 3rd‑party cookies:", options: ["True", "False", "Only Safari", "No"], correct: 0 },
//     { question: "ID Graph is:", options: ["Cross‑device ID map", "DSP tag", "Analytics tool", "Publisher feed"], correct: 0 },
//     { question: "Evercookies are:", options: ["Hard to delete", "Simple text feed", "Consent tag", "Analytics report"], correct: 0 },
//     { question: "Fingerprinting is:", options: ["Device signature", "Cookie type", "Budget method", "Auction type"], correct: 0 },
//   ],
//   data: [
//     { question: "DMP stands for:", options: ["Data Management Platform", "Digital Media Platform", "Display Marketing Platform", "Demand Management Platform"], correct: 0 },
//     { question: "1st‑party data is from:", options: ["Own site/app", "Third‑party provider", "DSP", "Publisher network"], correct: 0 },
//     { question: "Second‑party data is:", options: ["Partner data", "Public data", "CDP data", "DSP data"], correct: 0 },
//     { question: "Third‑party data is:", options: ["Purchased segments", "Own CRM", "Partner-only", "Site logs"], correct: 0 },
//     { question: "Onboarding means:", options: ["Uploading offline data", "Serving ads", "Tagging URLs", "Bid upload"], correct: 0 },
//     { question: "Audience segmentation means:", options: ["Grouping users", "Creating creatives", "Pricing inventory", "Collecting tags"], correct: 0 },
//     { question: "Pixels collect:", options: ["User behavior", "Bid prices", "Budget details", "Ad creatives"], correct: 0 },
//     { question: "APIs help to:", options: ["Connect systems", "Serve ads", "Track IDs only", "Block cookies"], correct: 0 },
//     { question: "Data enrichment means:", options: ["Enhancing profiles", "Budget pacing", "Ad serving", "Tagging only"], correct: 0 },
//     { question: "CDP =", options: ["Customer Data Platform", "Creative Design Platform", "Cookie Data Processor", "Campaign Delivery Platform"], correct: 0 },
//   ],
//   privacy: [
//     { question: "GDPR applies to:", options: ["EU personal data", "Global web", "US only", "Mobile only"], correct: 0 },
//     { question: "CCPA is from:", options: ["California", "Canada", "China", "Europe"], correct: 0 },
//     { question: "PII =", options: ["Personally Identifiable Information", "Private IP Info", "Public ID Index", "Personal Internet Identity"], correct: 0 },
//     { question: "ATT from Apple:", options: ["App Tracking Transparency", "Ad Tech Tool", "Analytics Tag Token", "Automated Tracking Tool"], correct: 0 },
//     { question: "Safari ITP blocks:", options: ["3rd‑party cookies", "1st‑party cookies", "HTML5 storage", "Device IDs"], correct: 0 },
//     { question: "Chrome plans to kill:", options: ["3rd‑party cookies", "First‑party cookies", "Ad tags", "CSS"], correct: 0 },
//     { question: "Opt‑out means user:", options: ["Declines behavioral ads", "Accepts cookies", "Clicks banners", "Shares data"], correct: 0 },
//     { question: "Ad blocker blocks:", options: ["Ads/scripts", "Campaigns", "Bid requests", "Audience segments"], correct: 0 },
//     { question: "SameSite cookie restricts:", options: ["Cross‑site sending", "Budget data", "Creative size", "DSP access"], correct: 0 },
//     { question: "Privacy Sandbox is by:", options: ["Google Chrome", "Safari", "Firefox", "Edge"], correct: 0 },
//   ],
//   fraud_view: [
//     { question: "Ad fraud type – bot traffic:", options: ["Automated fake visits", "Real human clicks", "Browser cookies", "Mobile IDs"], correct: 0 },
//     { question: "Domain spoofing is:", options: ["Misrepresenting site", "Tag error", "Creative fail", "Budget leak"], correct: 0 },
//     { question: "Viewability standard is:", options: ["50% for 1s", "100% for 1s", "5% for 3s", "75% for 2s"], correct: 0 },
//     { question: "Non‑human traffic =", options: ["Bots", "Users", "Cookies", "Tags"], correct: 0 },
//     { question: "Fraud hurts:", options: ["Advertiser ROI", "Campaign timing", "Creative size", "Volume only"], correct: 0 },
//     { question: "Viewable impression counts when:", options: ["50% pixels visible", "Page logs in", "User clicks", "Cookie sets"], correct: 0 },
//     { question: "Ad stacking =", options: ["Multiple ads layered", "Tag overlap", "ID sync", "Frequency cap"], correct: 0 },
//     { question: "Click fraud is:", options: ["Fake clicks", "Correct clicks", "Creative clicks", "Audio clicks"], correct: 0 },
//     { question: "Ad fraud defense uses:", options: ["Detection tools", "Creative tags", "Bid increase", "1st‑party data only"], correct: 0 },
//     { question: "Invalid traffic =", options: ["Bot/human invalid", "All traffic", "Creative only", "Tag only"], correct: 0 },
//   ],
// };

export const categories = [
  { id: 'basics',        name: 'Advertising Basics',        icon: '📚', color: 'from-blue-500 to-purple-600' },
  { id: 'history',       name: 'History of AdTech',         icon: '🕰️', color: 'from-green-500 to-teal-600' },
  { id: 'ecosystem',     name: 'Ad Ecosystem',              icon: '🌐', color: 'from-amber-500 to-orange-600' },
  { id: 'ad_serving',    name: 'Ad Serving',                icon: '🖥️', color: 'from-red-500 to-pink-600' },
  { id: 'targeting',     name: 'Targeting & Budget',        icon: '🎯', color: 'from-indigo-500 to-blue-600' },
  { id: 'media_buying',  name: 'Media Buying',              icon: '💼', color: 'from-emerald-500 to-cyan-600' },
  { id: 'identity',      name: 'User Identification',       icon: '🆔', color: 'from-yellow-500 to-red-600' },
  { id: 'data',          name: 'Data & DMPs',               icon: '💾', color: 'from-gray-500 to-gray-700' },
  { id: 'privacy',       name: 'Privacy & Compliance',      icon: '🔐', color: 'from-pink-500 to-purple-600' },
  { id: 'fraud_view',    name: 'Fraud & Viewability',       icon: '🚨', color: 'from-cyan-500 to-indigo-600' },
];

export const quizData = {
  basics: [
    { question: "In the digital advertising ecosystem, who is typically defined as the publisher and what is their primary role?", options: ["A company that creates and distributes advertising content to end users", "A website or app owner who provides digital real estate for displaying advertisements", "A technology platform that manages advertising campaigns and budgets", "A data analytics company that tracks user behavior across websites"], correct: 1 },
    { question: "What does the term 'AdTech' specifically encompass in the context of digital advertising?", options: ["Traditional marketing strategies and branding methodologies", "The suite of software tools, platforms, and technologies used to manage digital advertising", "Consumer behavior research and market analysis techniques", "Print and broadcast media advertising formats and standards"], correct: 1 },
    { question: "In a typical digital advertising transaction, who is ultimately responsible for paying the costs associated with ad placements?", options: ["The advertiser or brand seeking to promote their products or services", "The publisher who displays the advertisements on their digital properties", "The demand-side platform (DSP) that facilitates the media buying process", "The advertising agency that manages the campaign strategy and execution"], correct: 0 },
    { question: "From a business model perspective, what defines a publisher in the digital advertising landscape?", options: ["An entity that purchases advertising space to promote products or services", "A website, mobile app, or digital content owner who monetizes through ad inventory", "A third-party data provider that sells audience insights to advertisers", "A technology vendor that provides advertising exchange services"], correct: 1 },
    { question: "What does the acronym IAB represent in the digital advertising industry and what is its primary function?", options: ["Interactive Advertising Bureau - the industry standards organization", "Internet Advertising Board - a government regulatory body", "Integrated Ad Business - a trade association for agencies", "International Ad Broadcasting - a global media consortium"], correct: 0 },
    { question: "When advertisers discuss CPM pricing models, what specific metric are they referring to?", options: ["Cost per mile - the expense of running ads over geographic distances", "Clicks per minute - the rate of user engagement with advertisements", "Cost per mille - the price paid for one thousand ad impressions", "Click performance metric - a measure of advertisement effectiveness"], correct: 2 },
    { question: "What does the CTR metric specifically measure in digital advertising campaign performance?", options: ["Cost-to-revenue ratio - the financial efficiency of advertising spend", "Click-through rate - the percentage of users who click on an advertisement", "Conversion tracking rate - the number of completed purchase transactions", "Creative testing results - the effectiveness of different ad designs"], correct: 1 },
    { question: "What distinguishes rich media advertisements from standard display advertising formats?", options: ["They are limited to static images and basic text content only", "They support interactive elements, video, audio, and HTML5 animations", "They focus exclusively on simple text-based banner advertisements", "They are designed only for audio-based advertising experiences"], correct: 1 },
    { question: "In digital marketing, what is the primary purpose and mechanism of retargeting campaigns?", options: ["To exclusively target new users who have never visited the website", "To re-engage previous website visitors with personalized advertisements", "To drive organic search traffic through SEO optimization techniques", "To send push notifications directly to mobile device users"], correct: 1 },
    { question: "Who typically initiates, manages, and funds digital advertising campaigns in the advertising ecosystem?", options: ["Publishers who own the websites where ads are displayed", "Advertisers or brands who want to promote their products or services", "Both publishers and advertisers share equal responsibility for campaigns", "Government agencies that regulate digital advertising standards"], correct: 1 },
  ],
  history: [
    { question: "During which decade did digital advertising first emerge as a viable marketing channel?", options: ["The 1970s during the early computer networking era", "The 1990s with the rise of the World Wide Web", "The 2000s following the dot-com boom recovery", "The 2010s with the widespread adoption of social media"], correct: 1 },
    { question: "What year marked the debut of the first banner advertisement on the internet?", options: ["1994 on HotWired.com by AT&T", "1998 during the early Google search era", "2000 at the height of the dot-com bubble", "2002 following the internet advertising recovery"], correct: 0 },
    { question: "What technology did the earliest AdTech companies primarily rely on for user tracking and identification?", options: ["HTTP cookies for storing user identification data", "HTML5 local storage for cross-site tracking", "Mobile device IDs for user identification", "Artificial intelligence and machine learning algorithms"], correct: 0 },
    { question: "When did search engine advertising (like Google AdWords) first launch and revolutionize digital marketing?", options: ["1995 during the early web search engine development", "1998 when Google was founded as a search company", "2002 with the introduction of Google AdWords platform", "2005 during the expansion of paid search advertising"], correct: 2 },
    { question: "Around what time period did programmatic real-time bidding (RTB) become widely adopted in digital advertising?", options: ["2000 during the early dot-com advertising boom", "2007 alongside the introduction of ad exchanges", "2010 as programmatic technology matured and scaled", "2015 when header bidding began to challenge RTB"], correct: 2 },
    { question: "Which major technology company is credited with establishing the first dominant 'walled garden' advertising ecosystem?", options: ["YouTube through video advertising monetization", "Facebook with social media advertising platforms", "Google through search and display advertising networks", "Yahoo through portal-based advertising solutions"], correct: 2 },
    { question: "When did header bidding technology first start gaining adoption as an alternative to the traditional waterfall model?", options: ["2010 during the early programmatic advertising era", "2012 as real-time bidding technology matured", "2015 when publishers sought to increase ad revenue", "2018 following widespread programmatic adoption"], correct: 2 },
    { question: "In what time period did mobile advertising first begin to emerge as a significant advertising channel?", options: ["2000 with the introduction of WAP mobile internet", "2005 during the early smartphone development period", "2010 following the iPhone and Android smartphone adoption", "2015 when mobile traffic exceeded desktop usage"], correct: 1 },
    { question: "During which decade did ad blocking software become a mainstream concern for digital advertisers?", options: ["The 2010s as users became more privacy-conscious", "The 2000s during the early internet advertising growth", "The 1990s alongside the first web browsers", "The 1980s during early personal computer adoption"], correct: 0 },
    { question: "When did the General Data Protection Regulation (GDPR) officially take effect in the European Union?", options: ["2016 when the regulation was first approved", "2018 when enforcement officially began", "2020 during the COVID-19 pandemic period", "2022 following additional privacy regulation updates"], correct: 1 },
  ],
  ecosystem: [
    { question: "What does a Demand Side Platform (DSP) specifically enable in the programmatic advertising ecosystem?", options: ["A platform that allows advertisers to purchase ad inventory programmatically", "A data management system for storing publisher audience information", "A display advertising network for serving banner advertisements", "A demand forecasting tool for predicting advertising spending"], correct: 0 },
    { question: "In the digital advertising ecosystem, what role does a Supply Side Platform (SSP) primarily serve?", options: ["It operates on the sell-side, helping publishers monetize their ad inventory", "It functions on the buy-side, assisting advertisers with campaign management", "It serves as a neutral ad exchange facilitating programmatic transactions", "It provides advertiser-focused tools for campaign optimization and targeting"], correct: 0 },
    { question: "What is the primary function of an ad exchange in the programmatic advertising landscape?", options: ["To publish and distribute advertising content across multiple websites", "To serve as a marketplace auction venue for buying and selling ad inventory", "To provide analytics and reporting tools for campaign performance tracking", "To manage advertising tags and creative assets for publishers"], correct: 1 },
    { question: "Which of the following represents a classic example of a 'walled garden' advertising ecosystem?", options: ["An independent demand-side platform (DSP) serving multiple clients", "Google Ads platform with integrated search, display, and video advertising", "A third-party supply-side platform (SSP) working with various publishers", "An independent data broker providing audience insights to advertisers"], correct: 1 },
    { question: "Which organization is primarily responsible for establishing technical standards and best practices in digital advertising?", options: ["The World Wide Web Consortium (W3C)", "The Interactive Advertising Bureau (IAB)", "Internet Service Providers (ISPs)", "Major web browser development teams"], correct: 1 },
    { question: "How do publishers typically generate revenue from their digital advertising inventory?", options: ["By purchasing media placements from advertising networks", "By selling ad space and inventory to advertisers or through programmatic auctions", "By tracking user behavior and selling analytics data", "By providing consulting services and advertising analytics"], correct: 1 },
    { question: "Through what primary mechanism do advertisers typically purchase digital advertising inventory?", options: ["Directly through supply-side platforms (SSPs)", "Through demand-side platforms (DSPs) and programmatic buying", "By negotiating directly with individual publishers", "Through web browser advertising interfaces"], correct: 1 },
    { question: "What role do intermediaries play in the digital advertising ecosystem?", options: ["They serve as social media pages for brand marketing", "They facilitate connections between buyers and sellers, like ad exchanges", "They function as user agent strings in web browsers", "They operate as HTML tags embedded in web pages"], correct: 1 },
    { question: "In advertising ecosystem terminology, what does the 'buy-side' typically refer to?", options: ["Publishers who own websites and mobile applications", "Advertisers and brands who purchase advertising inventory", "Web browsers that display advertisements to users", "Industry standards organizations like the IAB"], correct: 1 },
    { question: "What does the 'sell-side' represent in the digital advertising ecosystem?", options: ["Demand-side platforms (DSPs) that purchase advertising inventory", "Supply-side platforms (SSPs) and publishers who sell ad space", "Advertising agencies that manage client campaigns", "Advertisers who create and fund marketing campaigns"], correct: 1 },
  ],
  ad_serving: [
    { question: "What is the primary function of an ad server in digital advertising campaign management?", options: ["To manage and optimize the delivery of advertising campaigns", "To collect and analyze user identification data across websites", "To upload and manage social media content feeds", "To create and enforce website privacy policies"], correct: 0 },
    { question: "In web development, what exactly is an advertising 'tag' and how does it function?", options: ["An HTML code snippet that calls and displays advertisements", "A high-resolution image file used for display advertising", "A video file format optimized for streaming advertisements", "A CSS stylesheet that controls advertisement appearance"], correct: 0 },
    { question: "Who typically hosts and manages first-party ad servers in the advertising ecosystem?", options: ["Publishers who own the websites where ads are displayed", "Demand-side platforms (DSPs) that purchase advertising inventory", "Supply-side platforms (SSPs) that sell advertising space", "The Interactive Advertising Bureau (IAB) standards organization"], correct: 0 },
    { question: "What is the primary capability of third-party ad servers in cross-site advertising?", options: ["They only track impression counts without user identification", "They track user identifiers and behavior across multiple websites", "They manage advertising budgets and campaign spending only", "They upload and distribute social media content feeds"], correct: 1 },
    { question: "When does the ad request process typically begin in the webpage loading sequence?", options: ["When the webpage begins loading and parsing HTML content", "After the advertising campaign budget has been fully spent", "When the user's advertising budget allocation is complete", "Only when a user actively clicks on an advertisement"], correct: 0 },
    { question: "In advertising terminology, what does the term 'creative' specifically refer to?", options: ["The actual advertisement content including images, text, and media", "A detailed user profile containing demographic information", "A supply-side platform (SSP) used for inventory management", "A demand-side platform (DSP) used for media buying"], correct: 0 },
    { question: "What type of information do advertising reports typically provide to campaign managers?", options: ["Campaign performance metrics including clicks, impressions, and conversions", "Server-side code and technical implementation details", "JavaScript code for campaign setup and configuration", "API keys and authentication tokens for platform access"], correct: 0 },
    { question: "How does increased latency in ad serving typically impact user experience and campaign performance?", options: ["It results in faster advertisement loading and better user experience", "It causes delays in page loading and potential revenue loss", "It leads to lower campaign budgets and reduced advertiser spending", "It increases bid prices and higher advertising costs"], correct: 1 },
    { question: "What core components are typically included in a comprehensive ad server technology stack?", options: ["Database management, logging systems, and tag management infrastructure", "Demand-side platform (DSP) integration code", "Cookie consent banners and privacy policy generators", "Game engine technology for interactive advertising"], correct: 0 },
    { question: "How does header bidding technology specifically change the traditional ad serving process?", options: ["It creates additional auction opportunities for advertisers", "It bypasses the traditional waterfall model for inventory allocation", "It eliminates the need for HTML tags in ad serving", "It replaces supply-side platforms (SSPs) entirely"], correct: 1 },
  ],
  targeting: [
    { question: "What type of data does contextual advertising targeting primarily analyze to determine ad placement?", options: ["Historical user behavior patterns and browsing history", "The content and context of the webpage where ads will be displayed", "Mobile device type and operating system specifications", "The bid price and budget allocation for advertising campaigns"], correct: 1 },
    { question: "What does behavioral targeting specifically focus on when determining advertisement relevance?", options: ["The textual content and keywords present on the current webpage", "User actions, browsing patterns, and historical online behavior", "IP address geolocation and geographic targeting data only", "Creative asset types and advertisement format specifications"], correct: 1 },
    { question: "How does retargeting technology identify and engage with potential customers?", options: ["By targeting completely new users who have never visited the website", "By re-engaging previous website visitors with personalized advertisements", "By using IP address geolocation for geographic targeting", "By analyzing mobile device types and specifications"], correct: 1 },
    { question: "What aspect of campaign delivery does dayparting specifically control and optimize?", options: ["The creative assets and visual design of advertisements", "The timing and scheduling of when advertisements are displayed", "The demographic age ranges of targeted users", "The budget allocation and spending limits for campaigns"], correct: 1 },
    { question: "Which organization provides the industry-standard taxonomy for content categorization in digital advertising?", options: ["The Interactive Advertising Bureau (IAB)", "Demand-side platforms (DSPs)", "Individual advertiser companies", "Publisher websites and applications"], correct: 0 },
    { question: "What primary data source does geo-targeting technology utilize to determine user location?", options: ["IP address geolocation and geographic data", "HTTP cookies stored in web browsers", "HTML tags embedded in web pages", "Creative assets and advertisement content"], correct: 0 },
    { question: "How does keyword targeting determine the relevance of advertisements to webpage content?", options: ["By analyzing user's browsing history and behavioral patterns", "By matching advertisement keywords to content keywords on the page", "By considering user demographic information and gender", "By evaluating mobile device types and technical specifications"], correct: 1 },
    { question: "What is the primary purpose of budget pacing in advertising campaign management?", options: ["To prevent campaigns from spending their entire budget too quickly", "To identify and resolve creative asset errors", "To reduce advertisement loading latency and improve performance", "To detect and prevent advertising fraud and invalid traffic"], correct: 0 },
    { question: "What types of criteria does device targeting typically include for advertisement optimization?", options: ["Specific device models, operating systems, and technical specifications", "User email addresses and contact information", "Website URLs and page navigation patterns", "Campaign identification numbers and tracking codes"], correct: 0 },
    { question: "How does section and URL targeting help advertisers optimize their campaign placement?", options: ["By targeting specific website sections and page categories", "By analyzing creative asset types and formats", "By managing user lists and audience segments", "By determining bid types and auction strategies"], correct: 0 },
  ],
  media_buying: [
    { question: "What does Real-Time Bidding (RTB) specifically enable in programmatic advertising?", options: ["Automated auction-based buying and selling of ad inventory in real-time", "Retargeting tools for re-engaging website visitors with personalized ads", "Responsive tag management for optimizing advertisement loading", "Rich media creative development with interactive elements"], correct: 0 },
    { question: "What distinguishes a Private Marketplace (PMP) from open programmatic advertising auctions?", options: ["A private, invitation-only marketplace for premium inventory trading", "A publisher-mediated program for content distribution", "A platform media program for cross-channel advertising", "A programmatic mediator plan for automated campaign management"], correct: 0 },
    { question: "What is the fundamental difference between header bidding and the traditional waterfall model?", options: ["Header bidding enables simultaneous auctions while waterfall uses sequential bidding", "Header bidding focuses on video content while waterfall handles display ads", "Header bidding targets mobile devices while waterfall targets desktop", "Header bidding serves buy-side needs while waterfall serves sell-side"], correct: 0 },
    { question: "In a first-price auction model, how much does the winning bidder pay for the advertising inventory?", options: ["The highest bidder pays their exact bid amount", "The highest bidder pays the second-highest bid plus a small increment", "The publisher pays the demand-side platform (DSP) directly", "No payment is required for winning bids"], correct: 0 },
    { question: "How does pricing work in a second-price auction system for digital advertising?", options: ["The winner pays the second-highest bid amount plus a small increment", "The winner pays their own original bid amount", "The winner pays only the reserve price set by the publisher", "No payment is charged for winning auction bids"], correct: 0 },
    { question: "What approach does the traditional waterfall model use for inventory allocation?", options: ["Sequential prioritization through multiple supply-side platforms (SSPs)", "Simultaneous header bidding auctions across all platforms", "Cookie synchronization for user identification", "Analytics-driven optimization for campaign performance"], correct: 0 },
    { question: "What type of transaction does programmatic direct specifically exclude from its process?", options: ["Real-time bidding (RTB) auctions", "Demand-side platform (DSP) integration", "Supply-side platform (SSP) connectivity", "Direct publisher relationship management"], correct: 0 },
    { question: "What characteristic defines manual media buying compared to programmatic approaches?", options: ["Non-automated, human-driven negotiation and purchasing processes", "Artificial intelligence-driven campaign optimization", "Real-time bidding and automated decision making", "Demand-side platform (DSP) based automated buying"], correct: 0 },
    { question: "What elements are typically included in programmatic auction dynamics?", options: ["Hard and soft price floors, bid shading, and reserve prices", "Privacy settings and user consent management", "Geographic targeting and location-based optimization", "Creative formats and advertisement asset specifications"], correct: 0 },
    { question: "How does a private marketplace (PMP) differ from open programmatic advertising exchanges?", options: ["It operates as an invitation-only real-time bidding environment", "It functions as a completely open auction accessible to all buyers", "It requires manual insertion orders and non-automated processes", "It operates through content delivery networks (CDNs) exclusively"], correct: 0 },
  ],
  identity: [
    { question: "What type of information do HTTP cookies primarily store for digital advertising purposes?", options: ["User identification data and behavioral tracking information", "Creative assets and advertisement content", "HTML tags and website code snippets", "Analytics reports and performance metrics only"], correct: 0 },
    { question: "What data sources does device fingerprinting technology typically utilize for user identification?", options: ["IP address, browser information, device specifications, and system settings", "Creative asset types and advertisement formats", "HTML tag patterns and website code structures", "Campaign budget amounts and spending allocations"], correct: 0 },
    { question: "Which mobile operating system uses IDFA (Identifier for Advertisers) for app-based tracking?", options: ["iOS devices including iPhone and iPad", "Android devices and mobile phones", "Desktop browsers and web applications", "Supply-side platforms (SSPs) exclusively"], correct: 0 },
    { question: "What does AAID stand for in the context of mobile advertising identification?", options: ["Android Advertising ID used for app tracking", "Apple Advertising Identifier for iOS devices", "Amazon Advertising ID for e-commerce tracking", "Advertiser Aggregated Identifier for campaign management"], correct: 0 },
    { question: "What does deterministic matching mean in the context of user identification and data linking?", options: ["Exact matching using known identifiers like email addresses", "Probabilistic matching based on behavior patterns", "Cookie synchronization processes only", "Anonymous matching without personal identifiers"], correct: 0 },
    { question: "What approach does probabilistic matching use for connecting user identities across devices?", options: ["Statistical inference and behavioral pattern analysis", "Direct identifier matching using known IDs", "Software development kit (SDK) integration only", "IP address matching exclusively"], correct: 0 },
    { question: "What is the current status of third-party cookie support across major web browsers?", options: ["Most browsers now block third-party cookies by default", "All browsers continue to support third-party cookies", "Only Safari blocks third-party cookies", "No browsers block third-party cookies"], correct: 0 },
    { question: "What is an ID Graph in the context of cross-device user identification?", options: ["A comprehensive map connecting user identities across multiple devices", "A demand-side platform (DSP) tagging system", "An analytics tool for campaign performance tracking", "A publisher feed for content distribution"], correct: 0 },
    { question: "What characteristic makes 'evercookies' particularly persistent in user tracking?", options: ["They are designed to be extremely difficult to delete", "They store simple text-based feed information", "They function as consent management tags", "They generate analytics reports automatically"], correct: 0 },
    { question: "What does device fingerprinting create to identify users across browsing sessions?", options: ["A unique digital signature based on device characteristics", "A specific type of HTTP cookie", "A budget management method for campaigns", "An auction type for programmatic buying"], correct: 0 },
  ],
  data: [
    { question: "What does a Data Management Platform (DMP) specifically provide for digital advertising campaigns?", options: ["A comprehensive system for collecting, organizing, and activating audience data", "A digital media platform for content distribution", "A display marketing platform for creative management", "A demand management platform for inventory allocation"], correct: 0 },
    { question: "What is the defining characteristic of first-party data in digital advertising?", options: ["Data collected directly from your own website, app, or customer interactions", "Data purchased from third-party data providers", "Data shared by demand-side platforms (DSPs)", "Data aggregated from publisher networks"], correct: 0 },
    { question: "How is second-party data typically obtained and what makes it valuable for advertisers?", options: ["Data shared directly from a trusted partner or business relationship", "Data available publicly through government sources", "Data managed by customer data platforms (CDPs)", "Data generated by demand-side platforms (DSPs)"], correct: 0 },
    { question: "What distinguishes third-party data from first-party and second-party data sources?", options: ["Data purchased from external providers who collected it from other sources", "Data from your own customer relationship management (CRM) system", "Data shared exclusively through partner relationships", "Data extracted from website server logs"], correct: 0 },
    { question: "What does the data onboarding process specifically accomplish for advertisers?", options: ["Uploading and integrating offline customer data into digital advertising platforms", "Serving advertisements to website visitors", "Adding HTML tags to website URLs", "Uploading bid information to advertising exchanges"], correct: 0 },
    { question: "What is the primary purpose of audience segmentation in digital advertising?", options: ["Grouping users based on shared characteristics and behaviors", "Creating visual creative assets for campaigns", "Setting pricing strategies for advertising inventory", "Collecting HTML tags from multiple websites"], correct: 0 },
    { question: "What type of data do tracking pixels primarily collect for advertising purposes?", options: ["User behavior data including page views, clicks, and conversions", "Bid prices and auction information", "Campaign budget details and spending limits", "Advertisement creative assets and content"], correct: 0 },
    { question: "What role do APIs (Application Programming Interfaces) play in digital advertising technology?", options: ["They enable different systems and platforms to connect and share data", "They serve advertisements directly to website visitors", "They track user IDs exclusively without other functions", "They block cookies and prevent user tracking"], correct: 0 },
    { question: "What does data enrichment accomplish in the context of audience development?", options: ["Enhancing user profiles with additional demographic and behavioral information", "Managing campaign budget pacing and spending limits", "Serving advertisements to targeted audiences", "Managing HTML tags and website code"], correct: 0 },
    { question: "What does CDP stand for and what is its primary function in marketing technology?", options: ["Customer Data Platform - unifies customer data from multiple sources", "Creative Design Platform - manages advertisement creative assets", "Cookie Data Processor - handles website cookie management", "Campaign Delivery Platform - manages advertisement serving"], correct: 0 },
  ],
  privacy: [
    { question: "What is the scope and jurisdiction of the General Data Protection Regulation (GDPR)?", options: ["European Union personal data protection regardless of where processing occurs", "Global web privacy regulation applicable worldwide", "United States federal privacy law exclusively", "Mobile application privacy regulation only"], correct: 0 },
    { question: "What U.S. state enacted the California Consumer Privacy Act (CCPA) privacy regulation?", options: ["California state government", "Canadian federal government", "Chinese national government", "European Union regulatory body"], correct: 0 },
    { question: "What does the acronym PII represent in privacy and data protection contexts?", options: ["Personally Identifiable Information that can identify specific individuals", "Private IP Information related to network addresses", "Public ID Index for user identification", "Personal Internet Identity for online accounts"], correct: 0 },
    { question: "What does Apple's App Tracking Transparency (ATT) framework specifically require?", options: ["App developers must request permission before tracking users across apps", "Ad technology tools must be approved by Apple", "Analytics tags must include token authentication", "Automated tracking tools must be disabled"], correct: 0 },
    { question: "What type of tracking technology does Safari's Intelligent Tracking Prevention (ITP) primarily block?", options: ["Third-party cookies and cross-site tracking", "First-party cookies from visited websites", "HTML5 local storage completely", "Mobile device identifiers"], correct: 0 },
    { question: "What significant change does Google Chrome plan to implement regarding cookie support?", options: ["Eliminating support for third-party cookies entirely", "Blocking first-party cookies from websites", "Removing HTML advertisement tags", "Disabling CSS stylesheets"], correct: 0 },
    { question: "What does it mean when a user chooses to 'opt-out' of behavioral advertising?", options: ["The user declines to receive behaviorally targeted advertisements", "The user accepts all cookies and tracking", "The user clicks on banner advertisements", "The user shares personal data with advertisers"], correct: 0 },
    { question: "What content do ad blockers typically prevent from loading on websites?", options: ["Advertisements, tracking scripts, and related advertising technology", "Entire marketing campaigns and strategies", "Programmatic bid requests and auctions", "Audience segments and targeting data"], correct: 0 },
    { question: "What does the SameSite cookie attribute specifically control in web browsers?", options: ["Restricts when cookies can be sent in cross-site requests", "Manages campaign budget data", "Controls creative asset size limits", "Restricts demand-side platform (DSP) access"], correct: 0 },
    { question: "Which company developed the Privacy Sandbox initiative for web privacy?", options: ["Google Chrome browser development team", "Apple Safari browser team", "Mozilla Firefox development team", "Microsoft Edge browser team"], correct: 0 },
  ],
  fraud_view: [
    { question: "What characterizes bot traffic as a form of digital advertising fraud?", options: ["Automated, non-human visits designed to generate false impressions and clicks", "Legitimate human clicks on advertisements", "Browser cookies used for user identification", "Mobile device identifiers for app tracking"], correct: 0 },
    { question: "What deceptive practice does domain spoofing involve in digital advertising fraud?", options: ["Misrepresenting the website where advertisements are actually being displayed", "HTML tag implementation errors", "Creative asset loading failures", "Campaign budget leakage and overspending"], correct: 0 },
    { question: "What is the industry standard definition for a viewable advertisement impression?", options: ["At least 50% of the ad pixels visible for at least 1 second", "100% of the ad pixels visible for at least 1 second", "At least 5% of the ad pixels visible for at least 3 seconds", "At least 75% of the ad pixels visible for at least 2 seconds"], correct: 0 },
    { question: "What does the term 'non-human traffic' specifically refer to in advertising fraud detection?", options: ["Bot traffic and automated systems generating fake interactions", "Real human users browsing websites", "HTTP cookies stored in browsers", "HTML tags embedded in web pages"], correct: 0 },
    { question: "How does advertising fraud primarily impact advertisers and their campaign performance?", options: ["It reduces advertiser return on investment (ROI) and wastes budget", "It only affects campaign timing and scheduling", "It impacts creative asset sizes and formats", "It affects campaign volume without financial impact"], correct: 0 },
    { question: "When does an advertisement impression count as 'viewable' according to industry standards?", options: ["When at least 50% of the ad pixels are visible on screen", "When the webpage successfully logs user information", "When a user actively clicks on the advertisement", "When an HTTP cookie is successfully set"], correct: 0 },
    { question: "What fraudulent practice does 'ad stacking' involve in digital advertising?", options: ["Layering multiple advertisements on top of each other", "HTML tag overlap and conflicts", "User identification synchronization across platforms", "Frequency capping for advertisement exposure"], correct: 0 },
    { question: "What constitutes click fraud in digital advertising and how does it harm advertisers?", options: ["Artificially generated clicks that don't represent genuine user interest", "Legitimate clicks from interested users", "Clicks on creative assets and content", "Audio-based clicks in streaming media"], correct: 0 },
    { question: "What methods do advertisers typically use to defend against advertising fraud?", options: ["Fraud detection tools and traffic verification services", "Creative asset tags and content management", "Bid price increases and budget adjustments", "First-party data collection exclusively"], correct: 0 },
    { question: "What does 'invalid traffic' encompass in digital advertising fraud prevention?", options: ["Both bot traffic and human traffic that doesn't meet quality standards", "All website traffic regardless of source", "Creative assets and content exclusively", "HTML tags and website code only"], correct: 0 },
  ],
};